name = "GridapPardiso"
uuid = "34aa2546-dee6-11e9-014e-739fa02ec06f"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
